name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the OS for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install numpy==1.24.4
        pip install spacy

    - name: Run tests
      run: |
        pytest  # Run tests using pytest

  deploy:
    runs-on: ubuntu-latest

    needs: build  # Ensure deployment only happens after the build and test steps succeed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server (or Docker/Kubernetes)
      run: |
        echo "Deploying to production"  # Add actual deployment commands here
        # E.g., using Docker:
        # docker build -t your-image-name .
        # docker push your-image-name
